/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package ly.count;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;

import org.appcelerator.titanium.TiApplication;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.kroll.common.TiConfig;

@Kroll.module(name = "Countly", id = "ly.count")
public class CountlyModule extends KrollModule {

	// Standard Debugging variables
	private static final String LCAT = "CountlyModule";
	private static final boolean DBG = TiConfig.LOGD;

	// You can define constants with @Kroll.constant, for example:
	// @Kroll.constant public static final String EXTERNAL_NAME = value;

	public CountlyModule() {
		super();
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app) {
		Log.d(LCAT, "inside onAppCreate");

		// put module init code that needs to run when the application is
		// created
	}

	// Methods
	@Kroll.method
	public void countInit(String url, String apiKey) {
		Log.d(LCAT, "Init called");
		Countly.sharedInstance().init(TiApplication.getAppCurrentActivity(),
				url, apiKey);
		Countly.sharedInstance().onStart();
	}

	@Kroll.method
	public void stopCount() {
		Log.d(LCAT, "Stop Count called");
		Countly.sharedInstance().onStop();
	}

	@Kroll.method
	public void sendEvent(String key, int count) {
		Log.d(LCAT, "Event Send called");
		Countly.sharedInstance().recordEvent(key, count);
	}

}
